#!/bin/sh

#EGSET=
EGSET=1

EWIFI=1
#EROOTPASS=1
ECRONREBOOT=1

if [ ! -z "$EGSET" ]; then

# set simplified chinese
uci set luci.main.lang=zh_cn
# uci set luci.main.mediaurlbase=Bootstap
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci add_list system.ntp.server="cn.pool.ntp.org"
uci add_list system.ntp.server="ntp.sjtu.edu.cn"

#uci network
#uci set network.lan.ipaddr='192.168.6.1'
#uci set network.lan.netmask='255.255.255.0'

#uci network of wan
#uci set network.wan.proto='pppoe'
#uci set network.wan.username='xxx'
#uci set network.wan.password='xxx'

#global ipv6 prefix
#uci set network.globals.ula_prefix='fd00:100:100::/48'

#uci commit system

#uci set fstab.@global[0].anon_mount=1
#uci commit fstab

# enable wifi
if [ ! -z "$EWIFI" ]; then
	uci set wireless.@wifi-device[0].disabled=0
	uci set wireless.@wifi-iface[0].disabled=0
	#uci set wireless.@wifi-iface[0].ssid='OpenWrt'
	#uci set wireless.@wifi-iface[0].encryption='psk-mixed or psk2'
	#uci set wireless.@wifi-iface[0].key='12345678'
    #uci set wireless.@wifi-iface[0].wds='1'

    #5G-wifi
	uci set wireless.@wifi-device[1].disabled=0
	uci set wireless.@wifi-iface[1].disabled=0
	#uci set wireless.@wifi-iface[1].ssid='OpenWrt-5G'
fi

# mirror of openwrt 
#sed -i 's/downloads.openwrt.org/mirrors.tuna.tsinghua.edu.cn\/openwrt/g' /etc/opkg/distfeeds.conf
#sed -i 's/downloads.openwrt.org/mirrors.ustc.edu.cn\/openwrt/g' /etc/opkg/distfeeds.conf
#sed -i 's/downloads.openwrt.org/mirror.sjtu.edu.cn\/openwrt/g' /etc/opkg/distfeeds.conf
#sed -i 's/downloads.openwrt.org/mirrors.ustc.edu.cn\/openwrt/g' /etc/opkg/distfeeds.conf
sed -i 's/downloads.openwrt.org/mirrors.cloud.tencent.com\/openwrt/g' /etc/opkg/distfeeds.conf

# root password(1-9)
[ ! -z "$EROOTPASS" ] && sed -i 's/root::0:0:99999:7:::/root:$1$FSKDB4kb$ySxGQwTAVLBH0s5B2dj29.:0:0:99999:7:::/g' /etc/shadow

if [ ! -z "$ECRONREBOOT" ]; then
#cron command for reboot 
egrep -q  "#30 4 * * * sleep 70 && touch /etc/banner && reboot "    /etc/crontabs/root ||
	echo  "#30 4 * * * sleep 70 && touch /etc/banner && reboot "   >> /etc/crontabs/root

#echo "*/5 * * * * dmesg | grep -q "Oops\|Tainted\|tained\|restart" && reboot"  >>  /etc/crontabs/root

echo "#wget --no-check-certificate https://raw.fastgit.org/521xueweihan/GitHub520/main/hosts -O /tmp/github520.txt && sed -i '/# GitHub520 Host Start/,/# Github520 Host End/d' /etc/hosts ; cat /tmp/github520.txt >> /etc/hosts ; /etc/init.d/dnsmasq restart" >> /etc/crontabs/root

fi

#dnsmasq setting
egrep -q "localise-queries"  /etc/dnsmasq.conf ||
	echo "localise-queries" >> /etc/dnsmasq.conf

egrep -q "bogus-priv"  /etc/dnsmasq.conf ||
	echo "bogus-priv" >> /etc/dnsmasq.conf

egrep -q  "expand-hosts"  /etc/dnsmasq.conf ||
	echo  "expand-hosts" >> /etc/dnsmasq.conf

#vlmcsd autoactivate
#egrep -q  "srv-host=_vlmcs._tcp.lan,OpenWrt.lan,1688,0,100"  /etc/dnsmasq.conf ||
#	echo  "srv-host=_vlmcs._tcp.lan,OpenWrt.lan,1688,0,100" >> /etc/dnsmasq.conf

#vlmcsd
#uci set vlmcsd.config.autoactivate=1
#uci commit vlmcsd

# Write everything to flash
#uci commit

fi   #endof EGSET

exit 0
